// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: sku.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sku struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Price         int32                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Num           int32                  `protobuf:"varint,4,opt,name=num,proto3" json:"num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sku) Reset() {
	*x = Sku{}
	mi := &file_sku_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sku) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sku) ProtoMessage() {}

func (x *Sku) ProtoReflect() protoreflect.Message {
	mi := &file_sku_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sku.ProtoReflect.Descriptor instead.
func (*Sku) Descriptor() ([]byte, []int) {
	return file_sku_proto_rawDescGZIP(), []int{0}
}

func (x *Sku) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Sku) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Sku) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Sku) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

var File_sku_proto protoreflect.FileDescriptor

const file_sku_proto_rawDesc = "" +
	"\n" +
	"\tsku.proto\"Q\n" +
	"\x03Sku\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price\x12\x10\n" +
	"\x03num\x18\x04 \x01(\x05R\x03num2+\n" +
	"\n" +
	"SkuService\x12\x1d\n" +
	"\rdecreaseStock\x12\x04.Sku\x1a\x04.Sku\"\x00B\vZ\t./;protosb\x06proto3"

var (
	file_sku_proto_rawDescOnce sync.Once
	file_sku_proto_rawDescData []byte
)

func file_sku_proto_rawDescGZIP() []byte {
	file_sku_proto_rawDescOnce.Do(func() {
		file_sku_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sku_proto_rawDesc), len(file_sku_proto_rawDesc)))
	})
	return file_sku_proto_rawDescData
}

var file_sku_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sku_proto_goTypes = []any{
	(*Sku)(nil), // 0: Sku
}
var file_sku_proto_depIdxs = []int32{
	0, // 0: SkuService.decreaseStock:input_type -> Sku
	0, // 1: SkuService.decreaseStock:output_type -> Sku
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sku_proto_init() }
func file_sku_proto_init() {
	if File_sku_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sku_proto_rawDesc), len(file_sku_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sku_proto_goTypes,
		DependencyIndexes: file_sku_proto_depIdxs,
		MessageInfos:      file_sku_proto_msgTypes,
	}.Build()
	File_sku_proto = out.File
	file_sku_proto_goTypes = nil
	file_sku_proto_depIdxs = nil
}
