version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234567
      # MYSQL_DATABASE: mydatabase
      # MYSQL_USER: myuser
      # MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    # volumes:
    #   - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.0
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
#     volumes:
#       - redis_data:/data

# volumes:
#   mysql_data:
#   redis_data: